### ISSUE TITLE
submitting projects

### ISSUE THREAD

**Issue by abmdev86** [abmdev86/discord-bot-1-quackbot#14]
submitting does nothing ```interaction.reply({ content: 'ok sir, message received' });```

**Comment by abmdev86** [comment]
``` ReferenceError: members is not defined
    at handleSubmitProject (C:\Users\AMweb\source\repos\discord-bot-1-quackbot\lib\eventHandlers.js:95:5)
    at async Object.execute (C:\Users\AMweb\source\repos\discord-bot-1-quackbot\events\interactionCreate.js:109:7)```
